### ISSUE TITLE
Using pip to install modules

### ISSUE THREAD

**Issue by tin2tin** [okuma10/ImportSubtitles#2]
If you want to add pip installing of external modules, it can be done like this:

```
import bpy, sys, subprocess, site

app_path = site.USER_SITE
if app_path not in sys.path:
    sys.path.append(app_path)

pybin = sys.executable  # bpy.app.binary_path_python # Use for 2.83

try:
    subprocess.call([pybin, "-m", "ensurepip"])
except ImportError:
    pass

try:
    import pysubs2
except ImportError:
    subprocess.check_call([pybin, "-m", "pip", "install", "pysubs2"])
    import pysubs2```

**Comment by okuma10** [comment]
does that add the module to blender's python? or it just loads it when it runs and drops it once you close blender?

**Comment by tin2tin** [comment]
It downloads and installs the pysub2 module into the Blender included python and stay there until you uninstall it, so you do not have to include it in your download.

**Comment by tin2tin** [comment]
(Noticed that github adds -main to your download folder, and it needs to be removed manually in order to get your add-on to work)

There is a nice add-on here to check out, update or uninstall the Blender included python add-ons: https://github.com/amb/blender_pip

**Comment by okuma10** [comment]
I tried your suggestion above and it added the module only while blender was running.

thanks for the github link...Will look it up

**Comment by tin2tin** [comment]
> I tried your suggestion above and it added the module only while blender was running.

It is installing the module into the Blender Python folder and should stay there until you manually uninstall it? Or maybe if you're on Windows you'll have to run Blender as admin?

**Comment by okuma10** [comment]
No it was my error I had two blenders running at that time. So it wasn't added, now it works as you said. Will add it and save the code for other addons I'm making.
Thanks a lot.

For the `-main` thing. I'm not sure why it wouldn't be working. I don't have hardcoded links. Everything is relative imports and using pathlib.

**Comment by tin2tin** [comment]
For the -main thing, I'm not able to reproduce now. Sorry.

**Comment by okuma10** [comment]
hey @tin2tin , I was wondering is there a way to remove the module only when the addon is removed(not disabled).
I noticed that blender doesn't have a "uninstall addon" feature(except through the API). I can check the status of the addon with addon_utils.check(). But as soon as you close blender, even if the addon is enabled in preferences, it will unregister the addon and if I have a function that removes the external modules, it will always remove them every time the software exits. Do you know if there is some setting or maybe file I can check to see if the addon is marked as enabled after blender shuts down?

**Comment by tin2tin** [comment]
I'm sorry I don't know that much about that stuff. Try to ask here: https://blender.chat/channel/python
